"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { ArrowRight, Check, ChevronRight, ExternalLink, Globe2, Layers3, SlidersHorizontal, Sparkles } from "lucide-react";
import { inferencePlatforms, modelLaunches, openModelCreators, providers, type Provider } from "@/lib/providers";
import { ProviderWorldMap } from "@/components/provider-world-map";
import { EcosystemLaunchTimeline } from "@/components/ecosystem-launch-timeline";
import { OpenModelSizing } from "@/components/open-model-sizing";

const categories = ["All", "Frontier lab", "Open-model lab", "Enterprise AI"] as const;

function ProviderMark({ provider, size = "md" }: { provider: Provider; size?: "sm" | "md" }) {
  return <span className={`flex ${size === "sm" ? "h-8 w-8 text-[10px]" : "h-11 w-11 text-xs"} items-center justify-center rounded-xl border border-white/10 font-semibold`} style={{ background: provider.colors.soft, color: provider.colors.primary }}>{provider.shortName}</span>;
}

function ProviderCard({ provider, selected, onToggle }: { provider: Provider; selected: boolean; onToggle: () => void }) {
  return <article className="group relative flex min-h-[270px] flex-col rounded-3xl border border-white/[.09] bg-[#0b1124]/80 p-5 shadow-[0_18px_55px_rgba(0,0,0,.16)] transition hover:-translate-y-1 hover:border-white/[.2] hover:bg-[#10182d]">
    <div className="flex items-start justify-between gap-4"><ProviderMark provider={provider}/><button onClick={onToggle} className={`flex h-7 min-w-7 items-center justify-center rounded-full border text-[10px] font-semibold transition ${selected ? "border-violet-300 bg-violet-500 text-white" : "border-white/12 text-slate-500 hover:border-violet-400 hover:text-violet-200"}`} aria-label={`${selected ? "Remove" : "Add"} ${provider.name} from comparison`}>{selected ? <Check className="h-3.5 w-3.5"/> : "+"}</button></div>
    <div className="mt-5"><div className="flex items-center gap-2"><h2 className="font-display text-xl font-semibold tracking-[-.03em] text-slate-100">{provider.name}</h2>{provider.openSource && <span className="rounded-full bg-emerald-400/10 px-1.5 py-0.5 text-[9px] font-semibold text-emerald-300">OPEN</span>}</div><p className="mt-1 text-[11px] text-slate-500">{provider.headquarters} · {provider.founded}</p><p className="mt-3 line-clamp-3 text-sm leading-6 text-slate-400">{provider.overview}</p></div>
    <div className="mt-auto pt-5"><div className="mb-4 flex flex-wrap gap-1.5">{provider.models.slice(0, 3).map((model) => <span key={model} className="rounded-md border border-white/[.07] bg-white/[.025] px-2 py-1 text-[10px] text-slate-400">{model}</span>)}</div><div className="flex items-center justify-between"><Link href={`/providers/${provider.slug}`} className="inline-flex items-center gap-1.5 text-xs font-semibold text-slate-200 hover:text-white">View profile <ArrowRight className="h-3.5 w-3.5 text-violet-300"/></Link><a href={provider.website} target="_blank" rel="noreferrer" className="rounded-lg p-1.5 text-slate-500 hover:bg-white/[.06] hover:text-slate-200" aria-label={`Visit ${provider.name} website`}><ExternalLink className="h-3.5 w-3.5"/></a></div></div>
  </article>;
}

export function ProviderDirectory() {
  const [category, setCategory] = useState<(typeof categories)[number]>("All");
  const [selected, setSelected] = useState<string[]>(["openai", "anthropic"]);
  const visibleProviders = useMemo(() => providers.filter((provider) => category === "All" || provider.category === category), [category]);
  const compareHref = `/compare?providers=${selected.join(",")}`;
  function toggleProvider(slug: string) { setSelected((current) => current.includes(slug) ? current.filter((item) => item !== slug) : current.length >= 4 ? [...current.slice(1), slug] : [...current, slug]); }

  return <main className="page-shell min-h-screen"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_20%_-10%,rgba(124,58,237,.18),transparent_28%),radial-gradient(circle_at_90%_8%,rgba(6,182,212,.12),transparent_26%)]"/>
    <nav className="relative z-10 mx-auto flex max-w-7xl items-center justify-between px-5 py-5 lg:px-8" aria-label="Main navigation"><Link href="/" className="flex items-center gap-2.5 font-display text-lg font-bold tracking-tight"><span className="flex h-8 w-8 items-center justify-center rounded-xl bg-gradient-to-br from-violet-500 via-indigo-500 to-cyan-400 shadow-lg shadow-violet-500/20"><Sparkles className="h-4 w-4"/></span>fusion<span className="text-slate-500">ai</span></Link><div className="hidden items-center gap-6 text-sm text-slate-400 md:flex"><a href="#map" className="hover:text-white">World map</a><a href="#timeline" className="hover:text-white">Timeline</a><a href="#directory" className="hover:text-white">Directory</a><a href="#sizing" className="hover:text-white">Sizing</a></div><Link href="/compare?providers=openai,anthropic" className="rounded-xl border border-white/10 bg-white/[.04] px-3 py-2 text-xs font-semibold text-slate-200 transition hover:bg-white/[.08]">Compare models</Link></nav>

    <section className="relative z-10 mx-auto max-w-7xl px-5 pb-16 pt-16 text-center sm:pb-24 sm:pt-24 lg:px-8"><div className="mx-auto inline-flex items-center gap-2 rounded-full border border-cyan-400/20 bg-cyan-400/[.08] px-3 py-1.5 text-xs font-medium text-cyan-100"><span className="h-1.5 w-1.5 rounded-full bg-cyan-300"/>A curated guide to the global GenAI model ecosystem</div><h1 className="font-display mx-auto mt-7 max-w-5xl text-5xl font-semibold leading-[.98] tracking-[-.055em] sm:text-7xl">Find the right <span className="gradient-text">AI model provider.</span></h1><p className="mx-auto mt-6 max-w-2xl text-base leading-7 text-slate-400 sm:text-lg">Fusion AI is an independent directory for discovering foundation-model labs, open-model creators, and the platforms that make them accessible.</p><div className="mx-auto mt-9 flex max-w-2xl flex-wrap justify-center gap-2 text-xs"><span className="rounded-full border border-white/[.1] bg-white/[.03] px-3 py-1.5 text-slate-300">{providers.length} providers</span><span className="rounded-full border border-white/[.1] bg-white/[.03] px-3 py-1.5 text-slate-300">{Object.values(modelLaunches).flat().length} documented launches</span><a href="#timeline" className="rounded-full border border-violet-400/25 bg-violet-500/[.1] px-3 py-1.5 font-medium text-violet-100 transition hover:bg-violet-500/[.18]">Explore release history</a></div></section>

    <ProviderWorldMap />

    <EcosystemLaunchTimeline />

    <section id="directory" className="relative z-10 mx-auto max-w-7xl scroll-mt-8 px-5 pb-24 lg:px-8"><div className="mb-7 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-violet-300">MODEL PROVIDERS</p><h2 className="font-display mt-2 text-3xl font-semibold tracking-[-.04em]">Browse the ecosystem</h2><p className="mt-2 text-sm text-slate-500">Every card links directly to the organization&apos;s official site and developer documentation.</p></div><div className="flex items-center gap-2 text-xs text-slate-500"><SlidersHorizontal className="h-3.5 w-3.5"/>Filter by organization type</div></div><div className="mb-6 flex gap-2 overflow-x-auto pb-1 scrollbar-hidden">{categories.map((item) => <button key={item} onClick={() => setCategory(item)} className={`whitespace-nowrap rounded-full border px-3 py-1.5 text-xs font-medium transition ${category === item ? "border-violet-400/30 bg-violet-500/15 text-violet-100" : "border-white/[.08] bg-white/[.025] text-slate-500 hover:text-slate-200"}`}>{item}</button>)}</div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{visibleProviders.map((provider) => <ProviderCard key={provider.slug} provider={provider} selected={selected.includes(provider.slug)} onToggle={() => toggleProvider(provider.slug)}/>)}</div>{visibleProviders.length === 0 && <div className="rounded-2xl border border-dashed border-white/10 py-16 text-center text-sm text-slate-500">No providers match that search. Try a model family or organization name.</div>}</section>

    <section id="open-models" className="relative z-10 mx-auto max-w-7xl scroll-mt-8 px-5 pb-24 lg:px-8"><div className="grid gap-6 rounded-[28px] border border-white/[.1] bg-gradient-to-br from-violet-500/[.11] to-cyan-500/[.045] p-6 sm:p-9 lg:grid-cols-[.75fr_1.25fr]"><div><div className="mb-4 flex h-10 w-10 items-center justify-center rounded-xl bg-violet-400/15 text-violet-200"><Layers3 className="h-5 w-5"/></div><p className="text-xs font-semibold uppercase tracking-[.16em] text-violet-200">OPEN MODEL CREATORS</p><h2 className="font-display mt-3 text-3xl font-semibold tracking-[-.04em]">For teams that need deployment freedom.</h2><p className="mt-4 text-sm leading-6 text-slate-400">Explore labs that publish open-weight models for self-hosted, partner-hosted, and local deployments. Always review the current license and model card before use.</p></div><div className="grid content-start gap-2 sm:grid-cols-2">{openModelCreators.map((creator) => <div key={creator} className="flex items-center gap-2 rounded-xl border border-white/[.08] bg-[#080e20]/65 px-3 py-3 text-xs text-slate-300"><span className="h-1.5 w-1.5 rounded-full bg-emerald-400"/>{creator}</div>)}</div></div></section>

    <OpenModelSizing />

    <section id="platforms" className="relative z-10 mx-auto max-w-7xl scroll-mt-8 px-5 pb-32 lg:px-8"><div className="mb-7"><p className="text-xs font-semibold uppercase tracking-[.16em] text-cyan-300">ONE API, MANY MODELS</p><h2 className="font-display mt-2 text-3xl font-semibold tracking-[-.04em]">Inference & aggregation platforms</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">These platforms can help teams access, route, host, or accelerate models from multiple providers.</p></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{inferencePlatforms.map((platform) => <a key={platform.name} href={platform.website} target="_blank" rel="noreferrer" className="group rounded-2xl border border-white/[.08] bg-[#0b1124]/70 p-4 transition hover:border-cyan-400/25 hover:bg-[#10182d]"><div className="flex items-center justify-between"><h3 className="font-display font-semibold text-slate-200">{platform.name}</h3><ExternalLink className="h-3.5 w-3.5 text-slate-600 transition group-hover:text-cyan-300"/></div><p className="mt-3 text-xs leading-5 text-slate-500">{platform.description}</p><span className="mt-4 inline-block text-[10px] font-medium text-cyan-300">{platform.access}</span></a>)}</div></section>

    {selected.length > 0 && <div className="fixed inset-x-0 bottom-0 z-30 border-t border-white/[.09] bg-[#0a1020]/92 px-4 py-3 backdrop-blur-xl"><div className="mx-auto flex max-w-4xl items-center justify-between gap-4"><div className="flex min-w-0 items-center gap-2"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-violet-500/15 text-violet-200"><Globe2 className="h-3.5 w-3.5"/></span><p className="truncate text-xs text-slate-400"><span className="font-semibold text-slate-200">{selected.length} provider{selected.length > 1 ? "s" : ""}</span> selected for comparison</p></div><Link href={compareHref} className="inline-flex shrink-0 items-center gap-1.5 rounded-lg bg-white px-3 py-2 text-xs font-semibold text-slate-950">Compare <ChevronRight className="h-3.5 w-3.5"/></Link></div></div>}
  </main>;
}
